name: CMake - Pull Request

on:
  [pull_request, workflow_dispatch]

env:
  BUILD_TYPE: Debug

jobs:
  linux_build:
    name: "Linux Build"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install ninja
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build
    - name: Configure CMake
      run: |
        cmake --version
        mkdir -p build
        cd build
        cmake -G "Ninja" .. -DCMAKE_BUILD_TYPE="${{env.BUILD_TYPE}}" -DCMAKE_C_COMPILER="/usr/bin/cc" -DCMAKE_CXX_COMPILER="/usr/bin/c++"
    - name: Build
      working-directory: ${{github.workspace}}/build
      run: |
        ninja
    - name: Test
      working-directory: ${{github.workspace}}/build/test
      run: |
        ./gTest


  windows_build:
    name: "Windows Build"
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: |
        cmake --version
        mkdir -p build
        cd build
        cmake -G "Ninja" .. -DCMAKE_BUILD_TYPE="${{env.BUILD_TYPE}}"
    - name: Build
      working-directory: ${{github.workspace}}/build
      run: |
        ninja
    - name: Test
      working-directory: ${{github.workspace}}/build/test
      run: |
        ./gTest
